name: Status Check
on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  check1:
    runs-on: ubuntu-latest

    steps:
      - name: something test1
        run: echo "something test1"

  check2:
    runs-on: ubuntu-latest

    steps:
      - name: something test2
        run: echo "something test2"